export const GET_PROCESSES_REQUEST = "GET_PROCESSES_REQUEST";
export const GET_PROCESSES_SUCCESS = "GET_PROCESSES_SUCCESS";
export const GET_PROCESSES_FAIL = "GET_PROCESSES_FAIL";
 
export const GET_PROCESS_DETAILS_REQUEST = "GET_PROCESS_DETAILS_REQUEST";
export const GET_PROCESS_DETAILS_SUCCESS = "GET_PROCESS_DETAILS_SUCCESS";
export const GET_PROCESS_DETAILS_FAIL = "GET_PROCESS_DETAILS_FAIL";
export const GET_PROCESS_DETAILS_RESET = "GET_PROCESS_DETAILS_RESET";
 

